const {eMeme, sMeme, all} = require("discord.js-memes")
const { MessageEmbed } = require('discord.js');

module.exports = {
  name: "meme",
  description: "sends a random meme from discord.js-memes package",
  aliases: ["pong"],
  permissions: ["CREATE_INVITE"],
  disabledChannel: [],
  category: "Administrator",
  cooldown: 8,
  /**
   * @param client {Client} A discord.js client
   * @param message {Message} A discord.js message
   * @param args {Array} A array of the arguments passed to the command
   * @returns {Promise<*>} Returns a promise that might return anything
   */
  run: async ({ client, message, args }) => {
    // create a time stamp with time and date
    const english = new eMeme()
    .setType(1)
    
    const memeEmbed = new MessageEmbed()
    .setTitle('Meme generated by `discord.js-memes`')
    .setImage(english)
    .setTimestamp()
    message.channel.send({ embeds: [memeEmbed] })
  },
};
